### PR TITLE
Add publish_skip parameter to supress high-frequency publishing of gripper sensor data

### PR DESCRIPTION
**Pull request by garaemon**
add ~publish_skip parameter to pr2_gripper_sensor_controller to skip publishing of sensor data.

cc: @h-kamada

### CODE REVIEW

**Comment by UltronDestroyer** [comment]
I think this should be done with nodehandle.advertise("topic_name", rate). There are cleaner ways to change the topic publisher rate than to use a modulus and an if statement.

**Comment by garaemon** [comment]
we cannot specify rate with `NodeHandle::advertise` method, the second argument is queue_size. 
http://docs.ros.org/indigo/api/roscpp/html/classros_1_1NodeHandle.html#a6b655c04f32c4c967d49799ff9312ac6

**Comment by UltronDestroyer** [comment]
Unfortunate, but you are right. This should definitely be inside the advertise topic. I'm going to make an issue on the Publisher page and see if this can't be set or else everyone's code will have a stupid if statement setup like this.

**Comment by garaemon** [comment]
> see if this can't be set or else everyone's code will have a stupid if statement setup like this.

Yeah, I think this kind of issues should be solved via good ROS-API.

Our problem is high-frequency of publishing sensor value causes too-much calling of subscribers such as the programs of pr2_sensor_gripper_action. In this case, the sensor values publish in 1000-Hz and callback funcitons of pr2_sensor_gripper_action are called 1000-Hz. And they consume about 50% of CPU.

**Comment by UltronDestroyer** [comment]
Hmm, there's no way to modify the code so that it doesn't publish at 1000HZ? That's weird. I always thought there was. I'll check ROS answers to be sure. 50% of CPU is enough to cause problems.

**Comment by trainman419** [comment]
ROS doesn't provide an external API to modify the topic rate; it's set implicitly by the rate at which publish is called on the publisher.

Given that this modifies one of core PR2 controllers, and it looks like there was already some unifinished work towards limiting the sensor publishing rate, @dbking77 should probably review it.

**Comment by dbking77** [comment]
I wish a could find a commit history, I can't remember much anymore.   However, I don't believe the gripper controller plug-in was not written by me.   I mostly dealt with the hardware interface that provides the data to the controllers.  

The actual data rate from the sensor is actually higher than 1khz, something like 3.5kHz.   Between 3-4 samples are returned each realtime cycle (1kHz).   The original motiviation for the high data rate was to do some filtering on the samples to to texture and impact detection.   I think Gunter wanted to do this, but never did.   The closest anybody got to doing this is Romano with the fist bumps. 

IMO, the fastest anybody probably should be publisheding to a ROS topic is about 100Hz, which would match the joint_states topic.   For stuff that needs higher rate data  somebody should be writing a plug-in controller that used the raw data and if needed publisheds a result at a lower rate.  
IMO the cost overhead of messages in ROS is way too high for 1kHz data rate.   

If fist bumps needs 1kHz data it should have a realtime controller that does the processing and otuputs a slower message if a fist bump was detected.  Another option for providing the full rate data  controller should batch mutliple samples into a message array and publish it at < 100Hz.

**Comment by UltronDestroyer** [comment]
After this answers.ros.org thread there were some suggestions. I think the best option would be to use this to throttle your node without modifying the code for now. 
http://wiki.ros.org/topic_tools/throttle

**Comment by garaemon** [comment]
I don't think throttle is a good solution. Because throttle itself consumes too much CPU.

In our environment on PR2, it uses about 6-8% CPU usage with 1khz slip_servo_state.

screenshot_from_2014-10-09 02 01 15

**Pull request merged**
